version: '2.1'
orbs:
  cypress: cypress-io/cypress@3
  node: circleci/node@5.0.2

executors:
  with browser:
    resource_class: small
    docker:
      -image: "cypress/browsers"
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          name: Chrome E2E Test
          yarn: true
          requires:
            - build-and-test
          start: yarn start
          executor: with-browser
          browser: chrome